protocols = pop3 lmtp
listen = *

ssl = required
ssl_cert = </run/mail-service-certs/fullchain.crt
ssl_key = </run/mail-service-certs/privkey.key
disable_plaintext_auth = yes
auth_mechanisms = plain login

mail_home = /var/mail/vhosts/%d/%n
mail_location = maildir:/var/mail/vhosts/%d/%n/Maildir
first_valid_uid = 1000

passdb {
  driver = passwd-file
  args = scheme=CRYPT username_format=%u /etc/dovecot/users.passwd
}

userdb {
  driver = static
  args = uid=vmail gid=vmail home=/var/mail/vhosts/%d/%n
}

service pop3-login {
  inet_listener pop3 {
    address = 0.0.0.0
    port = 110
  }
}

service lmtp {
  unix_listener /run/mail-service/dovecot-lmtp {
    mode = 0660
    user = vmail
    group = mail_service_sock
  }
}

service auth {
  unix_listener /run/mail-service/dovecot-auth {
    mode = 0660
    user = vmail
    group = mail_service_sock
  }
}

protocol lmtp {
  postmaster_address = postmaster@@@MAIL_DOMAIN@@
}

protocol pop3 {
  pop3_uidl_format = %08Xu%08Xv
}

log_path = /dev/stderr
info_log_path = /dev/stdout
