FROM docker.io/nginx:alpine

ARG GIT_BACKEND_SOCK_GID=4096

RUN set -eux; \
    sock_group="$(awk -F: -v gid="${GIT_BACKEND_SOCK_GID}" '$3 == gid {print $1; exit}' /etc/group)"; \
    if [ -z "${sock_group}" ]; then \
      addgroup -S -g "${GIT_BACKEND_SOCK_GID}" git_backend_sock; \
      sock_group=git_backend_sock; \
    fi; \
    if ! id -Gn nginx | grep -qw "${sock_group}"; then \
      addgroup nginx "${sock_group}"; \
    fi

COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
