server {
  listen 80;
  server_name _;

  client_max_body_size 0;

  location / {
    auth_basic "git-http-backend";
    auth_basic_user_file /etc/nginx/git_backend.htpasswd;

    include /etc/nginx/fastcgi_params;
    fastcgi_pass unix:/run/git-backend-fcgi/git-http-backend.sock;
    fastcgi_request_buffering off;
    fastcgi_buffering off;

    fastcgi_param SCRIPT_NAME /git-http-backend;
    fastcgi_param PATH_INFO $uri;
    fastcgi_param QUERY_STRING $query_string;
    fastcgi_param REQUEST_METHOD $request_method;
    fastcgi_param CONTENT_TYPE $content_type;
    fastcgi_param CONTENT_LENGTH $content_length;
    fastcgi_param REMOTE_USER $remote_user;
    fastcgi_param REMOTE_ADDR $http_x_real_ip;
    fastcgi_param GIT_PROJECT_ROOT /var/git/repos;
    fastcgi_param GIT_HTTP_EXPORT_ALL 1;
    fastcgi_param SCRIPT_FILENAME /usr/local/libexec/git-http-backend;
    fastcgi_param NO_BUFFERING "";
  }
}
