FROM ghcr.io/triliumnext/trilium:stable

USER root

RUN apk add --no-cache tzdata && \
    install -d -o node -g node -m 770 /trilium_backup

ARG TZ=Asia/Tokyo
ENV TZ=${TZ} \
    TRILIUM_BACKUP_DIR=/trilium_backup

RUN ln -sf "/usr/share/zoneinfo/${TZ}" /etc/localtime; \
    echo "${TZ}" > /etc/timezone
