FROM ghcr.io/triliumnext/trilium:stable

USER root

RUN apk add --no-cache tzdata

ARG TZ=Asia/Tokyo
ENV TZ=${TZ}

RUN ln -sf "/usr/share/zoneinfo/${TZ}" /etc/localtime; \
    echo "${TZ}" > /etc/timezone
